# infrastructure/monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # FastAPI backend (for health checks)
  - job_name: 'fastapi-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Node exporter for testing alerts
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['dummy-exporter:9100']
    scrape_interval: 10s

